{
    "openapi": "3.0.0",
    "info": {
        "title": "Data Gateway - GST verification",
        "description": "Build the data flow you needâ€”for customer onboarding, background verifications, and collecting electronic signatures.\n\n[See on Setu docs](https://docs.setu.co/data)",
        "contact": {},
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://dg-sandbox.setu.co",
            "variables": {}
        }
    ],
    "paths": {
        "/api/verify/gst": {
            "post": {
                "tags": ["GST"],
                "summary": "Verify GST",
                "operationId": "VerifyGST",
                "parameters": [
                    {
                        "name": "x-client-id",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "{{client_id}}"
                        }
                    },
                    {
                        "name": "x-client-secret",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "{{secret}}"
                        }
                    },
                    {
                        "name": "x-product-instance-id",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "{{x-product-instance-id}}"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/VerifyGSTRequest"
                                    },
                                    {
                                        "example": {
                                            "gstin": "27AAICA3918J1CT"
                                        }
                                    }
                                ]
                            },
                            "example": {
                                "gstin": "27AAICA3918J1CT"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "default no additional address": {
                        "description": "OK",
                        "headers": {},
                        "content": {
                            "application/json": {
                                "schema": {
                                    "allOf": [
                                        {
                                            "$ref": "#/components/schemas/ValidGST"
                                        },
                                        {
                                            "example": {
                                                "data": {
                                                    "address": {
                                                        "additional": [],
                                                        "principle": {
                                                            "buildingName": "MESH COMPLEX",
                                                            "buildingNumber": "WAREHOUSE H",
                                                            "city": "",
                                                            "district": "Thane",
                                                            "floorNo": "SURVEY NO. 35/4, 36/2",
                                                            "latitude": "",
                                                            "location": "BHIWANDI",
                                                            "longitude": "",
                                                            "naturePlaceOfBusiness": "",
                                                            "pinCode": "421302",
                                                            "stateCode": "Maharashtra",
                                                            "street": "SARAVALI"
                                                        }
                                                    },
                                                    "company": {
                                                        "constitutionOfBusiness": "Private Limited Company",
                                                        "name": "XYZ SELLER SERVICES PRIVATE LIMITED",
                                                        "natureOfBusinessActivity": "",
                                                        "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                                                        "status": "Active",
                                                        "taxPayerType": "Tax Collector (Electronic Commerce Operator)",
                                                        "tradeName": "XYZ SELLER SERVICES PRIVATE LIMITED",
                                                        "type": "Private Limited Company"
                                                    },
                                                    "gst": {
                                                        "dateOfCancellation": "",
                                                        "id": "27AAICB3918J1CT",
                                                        "lastUpdatedDate": "",
                                                        "registrationDate": "12/10/2018"
                                                    },
                                                    "jurisdiction": {
                                                        "centre": "Commissionerate - BHIWANDI,Division - DIVISION IV,Range - RANGE-I (Jurisdictional Office)",
                                                        "centreCode": "VQ0401",
                                                        "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                                                        "stateCode": "MHCG1425"
                                                    }
                                                },
                                                "message": "",
                                                "requestId": "e347e79b-dddc-49c1-b266-afb2c44843e8",
                                                "verification": "success",
                                                "traceId": "1-633f22e0-6eb8245d7043f93e1bf83604"
                                            }
                                        }
                                    ]
                                },
                                "example": {
                                    "data": {
                                        "address": {
                                            "additional": [],
                                            "principle": {
                                                "buildingName": "MESH COMPLEX",
                                                "buildingNumber": "WAREHOUSE H",
                                                "city": "",
                                                "district": "Thane",
                                                "floorNo": "SURVEY NO. 35/4, 36/2",
                                                "latitude": "",
                                                "location": "BHIWANDI",
                                                "longitude": "",
                                                "naturePlaceOfBusiness": "",
                                                "pinCode": "421302",
                                                "stateCode": "Maharashtra",
                                                "street": "SARAVALI"
                                            }
                                        },
                                        "company": {
                                            "constitutionOfBusiness": "Private Limited Company",
                                            "name": "XYZ SELLER SERVICES PRIVATE LIMITED",
                                            "natureOfBusinessActivity": "",
                                            "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                                            "status": "Active",
                                            "taxPayerType": "Tax Collector (Electronic Commerce Operator)",
                                            "tradeName": "XYZ SELLER SERVICES PRIVATE LIMITED",
                                            "type": "Private Limited Company"
                                        },
                                        "gst": {
                                            "dateOfCancellation": "",
                                            "id": "27AAICB3918J1CT",
                                            "lastUpdatedDate": "",
                                            "registrationDate": "12/10/2018"
                                        },
                                        "jurisdiction": {
                                            "centre": "Commissionerate - BHIWANDI,Division - DIVISION IV,Range - RANGE-I (Jurisdictional Office)",
                                            "centreCode": "VQ0401",
                                            "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                                            "stateCode": "MHCG1425"
                                        }
                                    },
                                    "message": "",
                                    "requestId": "e347e79b-dddc-49c1-b266-afb2c44843e8",
                                    "verification": "success",
                                    "traceId": "1-633f22e0-6eb8245d7043f93e1bf83604"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR",
                        "headers": {},
                        "content": {
                            "application/json": {
                                "schema": {
                                    "allOf": [
                                        {
                                            "$ref": "#/components/schemas/Errorresponse1"
                                        },
                                        {
                                            "example": {
                                                "error": {
                                                    "code": "upstream_error_response",
                                                    "detail": "error response from upstream.",
                                                    "requestId": "006425cd-7ebe-452a-9c0b-64e4df512324",
                                                    "traceId": "1-633c1b9c-0ab06611209a2b750b610d23"
                                                }
                                            }
                                        }
                                    ]
                                },
                                "example": {
                                    "error": {
                                        "code": "upstream_error_response",
                                        "detail": "error response from upstream.",
                                        "requestId": "006425cd-7ebe-452a-9c0b-64e4df512324",
                                        "traceId": "1-633c1b9c-0ab06611209a2b750b610d23"
                                    }
                                }
                            }
                        }
                    },
                    "200": {
                        "description": "OK",
                        "headers": {},
                        "content": {
                            "application/json": {
                                "schema": {
                                    "allOf": [
                                        {
                                            "$ref": "#/components/schemas/ValidGSTadditionaladdress"
                                        },
                                        {
                                            "example": {
                                                "data": {
                                                    "address": {
                                                        "additional": [
                                                            {
                                                                "buildingName": "",
                                                                "buildingNumber": "DOOR NO, 17",
                                                                "city": "",
                                                                "district": "Dakshina Kannada",
                                                                "floorNo": "1ST FLOOR",
                                                                "latitude": "",
                                                                "location": "ONNAKATTE KULAI OF MANGALORE",
                                                                "longitude": "",
                                                                "naturePlaceOfBusiness": "Office / Sale Office",
                                                                "pinCode": "575019",
                                                                "stateCode": "Karnataka",
                                                                "street": "XYZ COMPLEX OPP MAHILA MANDALA"
                                                            }
                                                        ],
                                                        "principle": {
                                                            "buildingName": "MESH COMPLEX",
                                                            "buildingNumber": "WAREHOUSE H",
                                                            "city": "",
                                                            "district": "Thane",
                                                            "floorNo": "SURVEY NO. 35/4, 36/2",
                                                            "latitude": "",
                                                            "location": "BHIWANDI",
                                                            "longitude": "",
                                                            "naturePlaceOfBusiness": "",
                                                            "pinCode": "421302",
                                                            "stateCode": "Maharashtra",
                                                            "street": "SARAVALI"
                                                        }
                                                    },
                                                    "company": {
                                                        "constitutionOfBusiness": "Private Limited Company",
                                                        "name": "XYZ SELLER SERVICES PRIVATE LIMITED",
                                                        "natureOfBusinessActivity": "",
                                                        "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                                                        "status": "Active",
                                                        "taxPayerType": "Tax Collector (Electronic Commerce Operator)",
                                                        "tradeName": "XYZ SELLER SERVICES PRIVATE LIMITED",
                                                        "type": "Private Limited Company"
                                                    },
                                                    "gst": {
                                                        "dateOfCancellation": "",
                                                        "id": "27AAICB3918J1CT",
                                                        "lastUpdatedDate": "",
                                                        "registrationDate": "12/10/2018"
                                                    },
                                                    "jurisdiction": {
                                                        "centre": "Commissionerate - BHIWANDI,Division - DIVISION IV,Range - RANGE-I (Jurisdictional Office)",
                                                        "centreCode": "VQ0401",
                                                        "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                                                        "stateCode": "MHCG1425"
                                                    }
                                                },
                                                "message": "",
                                                "requestId": "e347e79b-dddc-49c1-b266-afb2c44843e8",
                                                "verification": "success",
                                                "traceId": "1-633f22e0-6eb8245d7043f93e1bf83604"
                                            }
                                        }
                                    ]
                                },
                                "example": {
                                    "data": {
                                        "address": {
                                            "additional": [
                                                {
                                                    "buildingName": "",
                                                    "buildingNumber": "DOOR NO, 17",
                                                    "city": "",
                                                    "district": "Dakshina Kannada",
                                                    "floorNo": "1ST FLOOR",
                                                    "latitude": "",
                                                    "location": "ONNAKATTE KULAI OF MANGALORE",
                                                    "longitude": "",
                                                    "naturePlaceOfBusiness": "Office / Sale Office",
                                                    "pinCode": "575019",
                                                    "stateCode": "Karnataka",
                                                    "street": "XYZ COMPLEX OPP MAHILA MANDALA"
                                                }
                                            ],
                                            "principle": {
                                                "buildingName": "MESH COMPLEX",
                                                "buildingNumber": "WAREHOUSE H",
                                                "city": "",
                                                "district": "Thane",
                                                "floorNo": "SURVEY NO. 35/4, 36/2",
                                                "latitude": "",
                                                "location": "BHIWANDI",
                                                "longitude": "",
                                                "naturePlaceOfBusiness": "",
                                                "pinCode": "421302",
                                                "stateCode": "Maharashtra",
                                                "street": "SARAVALI"
                                            }
                                        },
                                        "company": {
                                            "constitutionOfBusiness": "Private Limited Company",
                                            "name": "XYZ SELLER SERVICES PRIVATE LIMITED",
                                            "natureOfBusinessActivity": "",
                                            "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                                            "status": "Active",
                                            "taxPayerType": "Tax Collector (Electronic Commerce Operator)",
                                            "tradeName": "XYZ SELLER SERVICES PRIVATE LIMITED",
                                            "type": "Private Limited Company"
                                        },
                                        "gst": {
                                            "dateOfCancellation": "",
                                            "id": "27AAICB3918J1CT",
                                            "lastUpdatedDate": "",
                                            "registrationDate": "12/10/2018"
                                        },
                                        "jurisdiction": {
                                            "centre": "Commissionerate - BHIWANDI,Division - DIVISION IV,Range - RANGE-I (Jurisdictional Office)",
                                            "centreCode": "VQ0401",
                                            "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                                            "stateCode": "MHCG1425"
                                        }
                                    },
                                    "message": "",
                                    "requestId": "e347e79b-dddc-49c1-b266-afb2c44843e8",
                                    "verification": "success",
                                    "traceId": "1-633f22e0-6eb8245d7043f93e1bf83604"
                                }
                            }
                        }
                    }
                },
                "deprecated": false,
                "security": []
            }
        }
    },
    "components": {
        "schemas": {
            "VerifyGSTRequest": {
                "title": "VerifyGSTRequest",
                "required": ["gstin"],
                "type": "object",
                "properties": {
                    "gstin": {
                        "type": "string"
                    }
                },
                "example": {
                    "gstin": "27AAICA3918J1CT"
                }
            },
            "ValidGST": {
                "title": "ValidGST",
                "required": [
                    "data",
                    "message",
                    "requestId",
                    "verification",
                    "traceId"
                ],
                "type": "object",
                "properties": {
                    "data": {
                        "$ref": "#/components/schemas/Data10"
                    },
                    "message": {
                        "type": "string"
                    },
                    "requestId": {
                        "type": "string"
                    },
                    "verification": {
                        "type": "string"
                    },
                    "traceId": {
                        "type": "string"
                    }
                },
                "example": {
                    "data": {
                        "address": {
                            "additional": [],
                            "principle": {
                                "buildingName": "MESH COMPLEX",
                                "buildingNumber": "WAREHOUSE H",
                                "city": "",
                                "district": "Thane",
                                "floorNo": "SURVEY NO. 35/4, 36/2",
                                "latitude": "",
                                "location": "BHIWANDI",
                                "longitude": "",
                                "naturePlaceOfBusiness": "",
                                "pinCode": "421302",
                                "stateCode": "Maharashtra",
                                "street": "SARAVALI"
                            }
                        },
                        "company": {
                            "constitutionOfBusiness": "Private Limited Company",
                            "name": "XYZ SELLER SERVICES PRIVATE LIMITED",
                            "natureOfBusinessActivity": "",
                            "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                            "status": "Active",
                            "taxPayerType": "Tax Collector (Electronic Commerce Operator)",
                            "tradeName": "XYZ SELLER SERVICES PRIVATE LIMITED",
                            "type": "Private Limited Company"
                        },
                        "gst": {
                            "dateOfCancellation": "",
                            "id": "27AAICB3918J1CT",
                            "lastUpdatedDate": "",
                            "registrationDate": "12/10/2018"
                        },
                        "jurisdiction": {
                            "centre": "Commissionerate - BHIWANDI,Division - DIVISION IV,Range - RANGE-I (Jurisdictional Office)",
                            "centreCode": "VQ0401",
                            "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                            "stateCode": "MHCG1425"
                        }
                    },
                    "message": "",
                    "requestId": "e347e79b-dddc-49c1-b266-afb2c44843e8",
                    "verification": "success",
                    "traceId": "1-633f22e0-6eb8245d7043f93e1bf83604"
                }
            },
            "Data10": {
                "title": "Data10",
                "required": ["address", "company", "gst", "jurisdiction"],
                "type": "object",
                "properties": {
                    "address": {
                        "$ref": "#/components/schemas/Address3"
                    },
                    "company": {
                        "$ref": "#/components/schemas/Company"
                    },
                    "gst": {
                        "$ref": "#/components/schemas/Gst"
                    },
                    "jurisdiction": {
                        "$ref": "#/components/schemas/Jurisdiction"
                    }
                },
                "example": {
                    "address": {
                        "additional": [],
                        "principle": {
                            "buildingName": "MESH COMPLEX",
                            "buildingNumber": "WAREHOUSE H",
                            "city": "",
                            "district": "Thane",
                            "floorNo": "SURVEY NO. 35/4, 36/2",
                            "latitude": "",
                            "location": "BHIWANDI",
                            "longitude": "",
                            "naturePlaceOfBusiness": "",
                            "pinCode": "421302",
                            "stateCode": "Maharashtra",
                            "street": "SARAVALI"
                        }
                    },
                    "company": {
                        "constitutionOfBusiness": "Private Limited Company",
                        "name": "XYZ SELLER SERVICES PRIVATE LIMITED",
                        "natureOfBusinessActivity": "",
                        "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                        "status": "Active",
                        "taxPayerType": "Tax Collector (Electronic Commerce Operator)",
                        "tradeName": "XYZ SELLER SERVICES PRIVATE LIMITED",
                        "type": "Private Limited Company"
                    },
                    "gst": {
                        "dateOfCancellation": "",
                        "id": "27AAICB3918J1CT",
                        "lastUpdatedDate": "",
                        "registrationDate": "12/10/2018"
                    },
                    "jurisdiction": {
                        "centre": "Commissionerate - BHIWANDI,Division - DIVISION IV,Range - RANGE-I (Jurisdictional Office)",
                        "centreCode": "VQ0401",
                        "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                        "stateCode": "MHCG1425"
                    }
                }
            },
            "Address3": {
                "title": "Address3",
                "required": ["additional", "principle"],
                "type": "object",
                "properties": {
                    "additional": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "description": ""
                    },
                    "principle": {
                        "$ref": "#/components/schemas/Principle"
                    }
                },
                "example": {
                    "additional": [],
                    "principle": {
                        "buildingName": "MESH COMPLEX",
                        "buildingNumber": "WAREHOUSE H",
                        "city": "",
                        "district": "Thane",
                        "floorNo": "SURVEY NO. 35/4, 36/2",
                        "latitude": "",
                        "location": "BHIWANDI",
                        "longitude": "",
                        "naturePlaceOfBusiness": "",
                        "pinCode": "421302",
                        "stateCode": "Maharashtra",
                        "street": "SARAVALI"
                    }
                }
            },
            "Principle": {
                "title": "Principle",
                "required": [
                    "buildingName",
                    "buildingNumber",
                    "city",
                    "district",
                    "floorNo",
                    "latitude",
                    "location",
                    "longitude",
                    "naturePlaceOfBusiness",
                    "pinCode",
                    "stateCode",
                    "street"
                ],
                "type": "object",
                "properties": {
                    "buildingName": {
                        "type": "string"
                    },
                    "buildingNumber": {
                        "type": "string"
                    },
                    "city": {
                        "type": "string"
                    },
                    "district": {
                        "type": "string"
                    },
                    "floorNo": {
                        "type": "string"
                    },
                    "latitude": {
                        "type": "string"
                    },
                    "location": {
                        "type": "string"
                    },
                    "longitude": {
                        "type": "string"
                    },
                    "naturePlaceOfBusiness": {
                        "type": "string"
                    },
                    "pinCode": {
                        "type": "string"
                    },
                    "stateCode": {
                        "type": "string"
                    },
                    "street": {
                        "type": "string"
                    }
                },
                "example": {
                    "buildingName": "MESH COMPLEX",
                    "buildingNumber": "WAREHOUSE H",
                    "city": "",
                    "district": "Thane",
                    "floorNo": "SURVEY NO. 35/4, 36/2",
                    "latitude": "",
                    "location": "BHIWANDI",
                    "longitude": "",
                    "naturePlaceOfBusiness": "",
                    "pinCode": "421302",
                    "stateCode": "Maharashtra",
                    "street": "SARAVALI"
                }
            },
            "Company": {
                "title": "Company",
                "required": [
                    "constitutionOfBusiness",
                    "name",
                    "natureOfBusinessActivity",
                    "state",
                    "status",
                    "taxPayerType",
                    "tradeName",
                    "type"
                ],
                "type": "object",
                "properties": {
                    "constitutionOfBusiness": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "natureOfBusinessActivity": {
                        "type": "string"
                    },
                    "state": {
                        "type": "string"
                    },
                    "status": {
                        "type": "string"
                    },
                    "taxPayerType": {
                        "type": "string"
                    },
                    "tradeName": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    }
                },
                "example": {
                    "constitutionOfBusiness": "Private Limited Company",
                    "name": "XYZ SELLER SERVICES PRIVATE LIMITED",
                    "natureOfBusinessActivity": "",
                    "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                    "status": "Active",
                    "taxPayerType": "Tax Collector (Electronic Commerce Operator)",
                    "tradeName": "XYZ SELLER SERVICES PRIVATE LIMITED",
                    "type": "Private Limited Company"
                }
            },
            "Gst": {
                "title": "Gst",
                "required": [
                    "dateOfCancellation",
                    "id",
                    "lastUpdatedDate",
                    "registrationDate"
                ],
                "type": "object",
                "properties": {
                    "dateOfCancellation": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "lastUpdatedDate": {
                        "type": "string"
                    },
                    "registrationDate": {
                        "type": "string"
                    }
                },
                "example": {
                    "dateOfCancellation": "",
                    "id": "27AAICB3918J1CT",
                    "lastUpdatedDate": "",
                    "registrationDate": "12/10/2018"
                }
            },
            "Jurisdiction": {
                "title": "Jurisdiction",
                "required": ["centre", "centreCode", "state", "stateCode"],
                "type": "object",
                "properties": {
                    "centre": {
                        "type": "string"
                    },
                    "centreCode": {
                        "type": "string"
                    },
                    "state": {
                        "type": "string"
                    },
                    "stateCode": {
                        "type": "string"
                    }
                },
                "example": {
                    "centre": "Commissionerate - BHIWANDI,Division - DIVISION IV,Range - RANGE-I (Jurisdictional Office)",
                    "centreCode": "VQ0401",
                    "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                    "stateCode": "MHCG1425"
                }
            },
            "InvalidGST": {
                "title": "InvalidGST",
                "required": [
                    "data",
                    "message",
                    "requestId",
                    "verification",
                    "traceId"
                ],
                "type": "object",
                "properties": {
                    "data": {
                        "type": "object"
                    },
                    "message": {
                        "type": "string"
                    },
                    "requestId": {
                        "type": "string"
                    },
                    "verification": {
                        "type": "string"
                    },
                    "traceId": {
                        "type": "string"
                    }
                },
                "example": {
                    "data": {},
                    "message": "Invalid GSTIN / UID",
                    "requestId": "f8baadba-5f92-481c-9ce4-f5ba45af030b",
                    "verification": "success",
                    "traceId": "1-633c15e8-24825b38477426d4165bb6c2"
                }
            },
            "Error81": {
                "title": "Error81",
                "required": ["code", "detail", "requestId", "traceId"],
                "type": "object",
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "detail": {
                        "type": "string"
                    },
                    "requestId": {
                        "type": "string"
                    },
                    "traceId": {
                        "type": "string"
                    }
                },
                "example": {
                    "code": "upstream_error_response",
                    "detail": "error response from upstream.",
                    "requestId": "006425cd-7ebe-452a-9c0b-64e4df512324",
                    "traceId": "1-633c1b9c-0ab06611209a2b750b610d23"
                }
            },
            "Errorresponse1": {
                "title": "Errorresponse1",
                "required": ["error"],
                "type": "object",
                "properties": {
                    "error": {
                        "$ref": "#/components/schemas/Error81"
                    }
                },
                "example": {
                    "error": {
                        "code": "upstream_error_response",
                        "detail": "error response from upstream.",
                        "requestId": "006425cd-7ebe-452a-9c0b-64e4df512324",
                        "traceId": "1-633c1b9c-0ab06611209a2b750b610d23"
                    }
                }
            },
            "ValidGSTadditionaladdress": {
                "title": "ValidGSTadditionaladdress",
                "required": [
                    "data",
                    "message",
                    "requestId",
                    "verification",
                    "traceId"
                ],
                "type": "object",
                "properties": {
                    "data": {
                        "$ref": "#/components/schemas/Data11"
                    },
                    "message": {
                        "type": "string"
                    },
                    "requestId": {
                        "type": "string"
                    },
                    "verification": {
                        "type": "string"
                    },
                    "traceId": {
                        "type": "string"
                    }
                },
                "example": {
                    "data": {
                        "address": {
                            "additional": [
                                {
                                    "buildingName": "",
                                    "buildingNumber": "DOOR NO, 17",
                                    "city": "",
                                    "district": "Dakshina Kannada",
                                    "floorNo": "1ST FLOOR",
                                    "latitude": "",
                                    "location": "ONNAKATTE KULAI OF MANGALORE",
                                    "longitude": "",
                                    "naturePlaceOfBusiness": "Office / Sale Office",
                                    "pinCode": "575019",
                                    "stateCode": "Karnataka",
                                    "street": "XYZ COMPLEX OPP MAHILA MANDALA"
                                }
                            ],
                            "principle": {
                                "buildingName": "MESH COMPLEX",
                                "buildingNumber": "WAREHOUSE H",
                                "city": "",
                                "district": "Thane",
                                "floorNo": "SURVEY NO. 35/4, 36/2",
                                "latitude": "",
                                "location": "BHIWANDI",
                                "longitude": "",
                                "naturePlaceOfBusiness": "",
                                "pinCode": "421302",
                                "stateCode": "Maharashtra",
                                "street": "SARAVALI"
                            }
                        },
                        "company": {
                            "constitutionOfBusiness": "Private Limited Company",
                            "name": "XYZ SELLER SERVICES PRIVATE LIMITED",
                            "natureOfBusinessActivity": "",
                            "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                            "status": "Active",
                            "taxPayerType": "Tax Collector (Electronic Commerce Operator)",
                            "tradeName": "XYZ SELLER SERVICES PRIVATE LIMITED",
                            "type": "Private Limited Company"
                        },
                        "gst": {
                            "dateOfCancellation": "",
                            "id": "27AAICB3918J1CT",
                            "lastUpdatedDate": "",
                            "registrationDate": "12/10/2018"
                        },
                        "jurisdiction": {
                            "centre": "Commissionerate - BHIWANDI,Division - DIVISION IV,Range - RANGE-I (Jurisdictional Office)",
                            "centreCode": "VQ0401",
                            "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                            "stateCode": "MHCG1425"
                        }
                    },
                    "message": "",
                    "requestId": "e347e79b-dddc-49c1-b266-afb2c44843e8",
                    "verification": "success",
                    "traceId": "1-633f22e0-6eb8245d7043f93e1bf83604"
                }
            },
            "Data11": {
                "title": "Data11",
                "required": ["address", "company", "gst", "jurisdiction"],
                "type": "object",
                "properties": {
                    "address": {
                        "$ref": "#/components/schemas/Address4"
                    },
                    "company": {
                        "$ref": "#/components/schemas/Company"
                    },
                    "gst": {
                        "$ref": "#/components/schemas/Gst"
                    },
                    "jurisdiction": {
                        "$ref": "#/components/schemas/Jurisdiction"
                    }
                },
                "example": {
                    "address": {
                        "additional": [
                            {
                                "buildingName": "",
                                "buildingNumber": "DOOR NO, 17",
                                "city": "",
                                "district": "Dakshina Kannada",
                                "floorNo": "1ST FLOOR",
                                "latitude": "",
                                "location": "ONNAKATTE KULAI OF MANGALORE",
                                "longitude": "",
                                "naturePlaceOfBusiness": "Office / Sale Office",
                                "pinCode": "575019",
                                "stateCode": "Karnataka",
                                "street": "XYZ COMPLEX OPP MAHILA MANDALA"
                            }
                        ],
                        "principle": {
                            "buildingName": "MESH COMPLEX",
                            "buildingNumber": "WAREHOUSE H",
                            "city": "",
                            "district": "Thane",
                            "floorNo": "SURVEY NO. 35/4, 36/2",
                            "latitude": "",
                            "location": "BHIWANDI",
                            "longitude": "",
                            "naturePlaceOfBusiness": "",
                            "pinCode": "421302",
                            "stateCode": "Maharashtra",
                            "street": "SARAVALI"
                        }
                    },
                    "company": {
                        "constitutionOfBusiness": "Private Limited Company",
                        "name": "XYZ SELLER SERVICES PRIVATE LIMITED",
                        "natureOfBusinessActivity": "",
                        "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                        "status": "Active",
                        "taxPayerType": "Tax Collector (Electronic Commerce Operator)",
                        "tradeName": "XYZ SELLER SERVICES PRIVATE LIMITED",
                        "type": "Private Limited Company"
                    },
                    "gst": {
                        "dateOfCancellation": "",
                        "id": "27AAICB3918J1CT",
                        "lastUpdatedDate": "",
                        "registrationDate": "12/10/2018"
                    },
                    "jurisdiction": {
                        "centre": "Commissionerate - BHIWANDI,Division - DIVISION IV,Range - RANGE-I (Jurisdictional Office)",
                        "centreCode": "VQ0401",
                        "state": "State - Maharashtra,Zone - Thane,Division - THANE CITY,Charge - BHIWANDI_701",
                        "stateCode": "MHCG1425"
                    }
                }
            },
            "Address4": {
                "title": "Address4",
                "required": ["additional", "principle"],
                "type": "object",
                "properties": {
                    "additional": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Additional"
                        },
                        "description": ""
                    },
                    "principle": {
                        "$ref": "#/components/schemas/Principle"
                    }
                },
                "example": {
                    "additional": [
                        {
                            "buildingName": "",
                            "buildingNumber": "DOOR NO, 17",
                            "city": "",
                            "district": "Dakshina Kannada",
                            "floorNo": "1ST FLOOR",
                            "latitude": "",
                            "location": "ONNAKATTE KULAI OF MANGALORE",
                            "longitude": "",
                            "naturePlaceOfBusiness": "Office / Sale Office",
                            "pinCode": "575019",
                            "stateCode": "Karnataka",
                            "street": "XYZ COMPLEX OPP MAHILA MANDALA"
                        }
                    ],
                    "principle": {
                        "buildingName": "MESH COMPLEX",
                        "buildingNumber": "WAREHOUSE H",
                        "city": "",
                        "district": "Thane",
                        "floorNo": "SURVEY NO. 35/4, 36/2",
                        "latitude": "",
                        "location": "BHIWANDI",
                        "longitude": "",
                        "naturePlaceOfBusiness": "",
                        "pinCode": "421302",
                        "stateCode": "Maharashtra",
                        "street": "SARAVALI"
                    }
                }
            },
            "Additional": {
                "title": "Additional",
                "required": [
                    "buildingName",
                    "buildingNumber",
                    "city",
                    "district",
                    "floorNo",
                    "latitude",
                    "location",
                    "longitude",
                    "naturePlaceOfBusiness",
                    "pinCode",
                    "stateCode",
                    "street"
                ],
                "type": "object",
                "properties": {
                    "buildingName": {
                        "type": "string"
                    },
                    "buildingNumber": {
                        "type": "string"
                    },
                    "city": {
                        "type": "string"
                    },
                    "district": {
                        "type": "string"
                    },
                    "floorNo": {
                        "type": "string"
                    },
                    "latitude": {
                        "type": "string"
                    },
                    "location": {
                        "type": "string"
                    },
                    "longitude": {
                        "type": "string"
                    },
                    "naturePlaceOfBusiness": {
                        "type": "string"
                    },
                    "pinCode": {
                        "type": "string"
                    },
                    "stateCode": {
                        "type": "string"
                    },
                    "street": {
                        "type": "string"
                    }
                },
                "example": {
                    "buildingName": "",
                    "buildingNumber": "DOOR NO, 17",
                    "city": "",
                    "district": "Dakshina Kannada",
                    "floorNo": "1ST FLOOR",
                    "latitude": "",
                    "location": "ONNAKATTE KULAI OF MANGALORE",
                    "longitude": "",
                    "naturePlaceOfBusiness": "Office / Sale Office",
                    "pinCode": "575019",
                    "stateCode": "Karnataka",
                    "street": "XYZ COMPLEX OPP MAHILA MANDALA"
                }
            }
        },
        "securitySchemes": {
            "bearer": {
                "type": "http",
                "scheme": "bearer"
            }
        }
    },
    "security": [
        {
            "bearer": []
        }
    ],
    "tags": [
        {
            "name": "GST"
        },
        {
            "name": "Misc",
            "description": ""
        }
    ]
}
