{
  "openapi": "3.0.0",
  "info": {
    "title": "Data Gateway - Bank account verification (Reverse Penny drop)",
    "description": "**Bank Account Verification**\nConfirm the validity of an account from the account holderâ€™s bank, with reverse penny-drop (Get the user to penny-drop via UPI!). ",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://dg-sandbox.setu.co",
      "variables": {}
    }
  ],
  "paths": {
    "/api/verify/ban/reverse": {
      "post": {
        "tags": [
          "Reverse Penny Drop"
        ],
        "summary": "Create RPD (without body)",
        "operationId": "CreateRPD(withoutbody)",
        "parameters": [
          {
            "name": "x-client-id",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{client_id}}"
            }
          },
          {
            "name": "x-client-secret",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{secret}}"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "CREATED",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Success10"
                    },
                    {
                      "example": {
                        "id": "81f4d2dd-6d32-48b0-8060-4976ea7acffc",
                        "shortUrl": "https://sandbox.bills.pe/4qb3gymfvq2j",
                        "status": "BAV_REVERSE_PENNY_DROP_CREATED",
                        "traceId": "1-6348f219-48d54db111bd597b588d8ebb",
                        "upiBillId": "1005098383142028542",
                        "upiLink": "upi://pay?pa=bauvatest@kaypay&pn=BauvaTest&am=1.00&tr=1005098383142028542&tn=Account%20Verification&cu=INR&mode=04",
                        "validUpto": "2022-10-14T05:25:34.087479"
                      }
                    }
                  ]
                },
                "example": {
                  "id": "81f4d2dd-6d32-48b0-8060-4976ea7acffc",
                  "shortUrl": "https://sandbox.bills.pe/4qb3gymfvq2j",
                  "status": "BAV_REVERSE_PENNY_DROP_CREATED",
                  "traceId": "1-6348f219-48d54db111bd597b588d8ebb",
                  "upiBillId": "1005098383142028542",
                  "upiLink": "upi://pay?pa=bauvatest@kaypay&pn=BauvaTest&am=1.00&tr=1005098383142028542&tn=Account%20Verification&cu=INR&mode=04",
                  "validUpto": "2022-10-14T05:25:34.087479"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "headers": {  
            },
            "content": {
              "application/octet-stream": {
                "schema": {
                  "type": "string",
                  "example": "response indicates failure, status=401, body={\"error\":\"unauthorized_client\",\"error_description\":\"Invalid client secret\"}\n"
                },
                "example": "response indicates failure, status=401, body={\"error\":\"unauthorized_client\",\"error_description\":\"Invalid client secret\"}\n"
              }
            }
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/verify/ban/reverse/mock_payment/{requestId}": {
      "post": {
        "tags": [
          "Reverse Penny Drop"
        ],
        "summary": "Mock Payment",
        "operationId": "MockPayment",
        "parameters": [
          {
            "name": "requestId",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{request_id}}"
            }
          },
          {
            "name": "x-client-id",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{client_id}}"
            }
          },
          {
            "name": "x-client-secret",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{secret}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {  
            },
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Success12"
                    },
                    {
                      "example": {
                        "success": true,
                        "traceId": "1-6348f340-742786432dd0e7e13bdbc7a4"
                      }
                    }
                  ]
                },
                "example": {
                  "success": true,
                  "traceId": "1-6348f340-742786432dd0e7e13bdbc7a4"
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/api/verify/ban/reverse/{requestId}": {
      "get": {
        "tags": [
          "Reverse Penny Drop"
        ],
        "summary": "Get Details",
        "operationId": "GetDetails",
        "parameters": [
          {
            "name": "requestId",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{request_id}}"
            }
          },
          {
            "name": "x-client-id",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{client_id}}"
            }
          },
          {
            "name": "x-client-secret",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{secret}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
            },
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Success13"
                    },
                    {
                      "example": {
                        "additionalData": null,
                        "data": {
                          "accountType": "UNKNOWN",
                          "bankAccountIfsc": "SETU0000012",
                          "bankAccountName": "Noresh",
                          "bankAccountNumber": "9009120939129",
                          "ifscCrossCheck": false,
                          "payerVpa": "customer@vpa"
                        },
                        "id": "1af36b4e-681e-48a2-a15c-3b92da00e4c4",
                        "shortUrl": "https://sandbox.bills.pe/vnl056cniwrk",
                        "status": "BAV_REVERSE_PENNY_DROP_PAYMENT_SUCCESSFUL",
                        "traceId": "1-6348f366-55c47bbe132d78441bbe4623",
                        "upiBillId": "1005100812449350916",
                        "upiLink": "upi://pay?pa=bauvatest@kaypay&pn=BauvaTest&am=1.00&tr=1005100812449350916&tn=Account%20Verification&cu=INR&mode=04",
                        "validUpto": "2022-10-14T05:30:23.683631"
                      }
                    }
                  ]
                },
                "example": {
                  "additionalData": null,
                  "data": {
                    "accountType": "UNKNOWN",
                    "bankAccountIfsc": "SETU0000012",
                    "bankAccountName": "Noresh",
                    "bankAccountNumber": "9009120939129",
                    "ifscCrossCheck": false,
                    "payerVpa": "customer@vpa"
                  },
                  "id": "1af36b4e-681e-48a2-a15c-3b92da00e4c4",
                  "shortUrl": "https://sandbox.bills.pe/vnl056cniwrk",
                  "status": "BAV_REVERSE_PENNY_DROP_PAYMENT_SUCCESSFUL",
                  "traceId": "1-6348f366-55c47bbe132d78441bbe4623",
                  "upiBillId": "1005100812449350916",
                  "upiLink": "upi://pay?pa=bauvatest@kaypay&pn=BauvaTest&am=1.00&tr=1005100812449350916&tn=Account%20Verification&cu=INR&mode=04",
                  "validUpto": "2022-10-14T05:30:23.683631"
                }
              }
            }
          },
          "200 with ifsc details": {
            "description": "OK",
            "headers": {
            },
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Success13"
                    },
                    {
                      "example": {
                        "additionalData": null,
                        "data": {
                          "accountType": "UNKNOWN",
                          "bankAccountIfsc": "SETU0000012",
                          "bankAccountName": "Noresh",
                          "bankAccountNumber": "9009120939129",
                          "ifscCrossCheck": false,
                          "ifscDetails": {
                            "address": "GANDHI ROAD  DISTT  KANCHIPURAM  TAMIL NADU  602105",
                            "branch": "SRIPERUMBUDUR",
                            "center": "KANCHEEPURAM",
                            "city": "SRIPERUMBUDUR",
                            "contact": "",
                            "district": "KANCHEEPURAM",
                            "imps": "true",
                            "iso3166": "IN-TN",
                            "micr": "600002113",
                            "name": "State Bank of India",
                            "neft": "true",
                            "rtgs": "true",
                            "state": "TAMIL NADU",
                            "swift": "",
                            "upi": "true"
                        },
                          "payerVpa": "customer@vpa"
                        },
                        "id": "1af36b4e-681e-48a2-a15c-3b92da00e4c4",
                        "shortUrl": "https://sandbox.bills.pe/vnl056cniwrk",
                        "status": "BAV_REVERSE_PENNY_DROP_PAYMENT_SUCCESSFUL",
                        "traceId": "1-6348f366-55c47bbe132d78441bbe4623",
                        "upiBillId": "1005100812449350916",
                        "upiLink": "upi://pay?pa=bauvatest@kaypay&pn=BauvaTest&am=1.00&tr=1005100812449350916&tn=Account%20Verification&cu=INR&mode=04",
                        "validUpto": "2022-10-14T05:30:23.683631"
                      }
                    }
                  ]
                },
                "example": {
                  "additionalData": null,
                  "data": {
                    "accountType": "UNKNOWN",
                    "bankAccountIfsc": "SETU0000012",
                    "bankAccountName": "Noresh",
                    "bankAccountNumber": "9009120939129",
                    "ifscCrossCheck": false,
                    "payerVpa": "customer@vpa"
                  },
                  "id": "1af36b4e-681e-48a2-a15c-3b92da00e4c4",
                  "shortUrl": "https://sandbox.bills.pe/vnl056cniwrk",
                  "status": "BAV_REVERSE_PENNY_DROP_PAYMENT_SUCCESSFUL",
                  "traceId": "1-6348f366-55c47bbe132d78441bbe4623",
                  "upiBillId": "1005100812449350916",
                  "upiLink": "upi://pay?pa=bauvatest@kaypay&pn=BauvaTest&am=1.00&tr=1005100812449350916&tn=Account%20Verification&cu=INR&mode=04",
                  "validUpto": "2022-10-14T05:30:23.683631"
                }
              }
            }
          },
          "404": {
            "description": "NOT FOUND",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Failure-NotFound1"
                    },
                    {
                      "example": {
                        "error": {
                          "code": "request_not_found",
                          "detail": "Unable to find the BAV reverse penny drop request.",
                          "traceId": "1-6348f37d-0a98296b43325b78627a65a7"
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "error": {
                    "code": "request_not_found",
                    "detail": "Unable to find the BAV reverse penny drop request.",
                    "traceId": "1-6348f37d-0a98296b43325b78627a65a7"
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/auth/realms/datagateway/protocol/openid-connect/token": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Get Auth token",
        "operationId": "GetAuthtoken",
        "parameters": [],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "encoding": {},
              "schema": {
                "required": [
                  "grant_type",
                  "client_id",
                  "client_secret"
                ],
                "type": "object",
                "properties": {
                  "grant_type": {
                    "type": "string",
                    "example": "client_credentials"
                  },
                  "client_id": {
                    "type": "string",
                    "example": "{{client_id}}"
                  },
                  "client_secret": {
                    "type": "string",
                    "example": "{{secret}}"
                  }
                }
              }
            }
          },
          "required": false
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "Error": {
        "title": "Error",
        "required": [
          "code",
          "detail",
          "traceId"
        ],
        "type": "object",
        "properties": {
          "code": {
            "type": "string"
          },
          "detail": {
            "type": "string"
          },
          "traceId": {
            "type": "string"
          }
        },
        "example": {
          "code": "invalid_document",
          "detail": "The document Id is already being used in a signature",
          "traceId": ""
        }
      },
      "Success10": {
        "title": "Success10",
        "required": [
          "id",
          "shortUrl",
          "status",
          "traceId",
          "upiBillId",
          "upiLink",
          "validUpto"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "shortUrl": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "traceId": {
            "type": "string"
          },
          "upiBillId": {
            "type": "string"
          },
          "upiLink": {
            "type": "string"
          },
          "validUpto": {
            "type": "string"
          }
        },
        "example": {
          "id": "81f4d2dd-6d32-48b0-8060-4976ea7acffc",
          "shortUrl": "https://sandbox.bills.pe/4qb3gymfvq2j",
          "status": "BAV_REVERSE_PENNY_DROP_CREATED",
          "traceId": "1-6348f219-48d54db111bd597b588d8ebb",
          "upiBillId": "1005098383142028542",
          "upiLink": "upi://pay?pa=bauvatest@kaypay&pn=BauvaTest&am=1.00&tr=1005098383142028542&tn=Account%20Verification&cu=INR&mode=04",
          "validUpto": "2022-10-14T05:25:34.087479"
        }
      },
      "CreateRPDwithbodyRequest": {
        "title": "CreateRPDwithbodyRequest",
        "required": [
          "additionalData"
        ],
        "type": "object",
        "properties": {
          "additionalData": {
            "$ref": "#/components/schemas/AdditionalData"
          }
        },
        "example": {
          "additionalData": {
            "key1": "value1",
            "key2": "value2"
          }
        }
      },
      "AdditionalData": {
        "title": "AdditionalData",
        "required": [
          "key1",
          "key2"
        ],
        "type": "object",
        "properties": {
          "key1": {
            "type": "string"
          },
          "key2": {
            "type": "string"
          }
        },
        "example": {
          "key1": "value1",
          "key2": "value2"
        }
      },
      "Success12": {
        "title": "Success12",
        "required": [
          "success",
          "traceId"
        ],
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "traceId": {
            "type": "string"
          }
        },
        "example": {
          "success": true,
          "traceId": "1-6348f340-742786432dd0e7e13bdbc7a4"
        }
      },
      "Failure": {
        "title": "Failure",
        "required": [
          "success",
          "traceId"
        ],
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "traceId": {
            "type": "string"
          }
        },
        "example": {
          "success": false,
          "traceId": "1-6348f340-742786432dd0e7e13bdbc7a4"
        }
      },
      "Success13": {
        "title": "Success13",
        "required": [
          "additionalData",
          "data",
          "id",
          "shortUrl",
          "status",
          "traceId",
          "upiBillId",
          "upiLink",
          "validUpto"
        ],
        "type": "object",
        "properties": {
          "additionalData": {
            "type": "string",
            "nullable": true
          },
          "data": {
            "$ref": "#/components/schemas/Data3"
          },
          "id": {
            "type": "string"
          },
          "shortUrl": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "traceId": {
            "type": "string"
          },
          "upiBillId": {
            "type": "string"
          },
          "upiLink": {
            "type": "string"
          },
          "validUpto": {
            "type": "string"
          }
        },
        "example": {
          "additionalData": null,
          "data": {
            "accountType": "UNKNOWN",
            "bankAccountIfsc": "SETU0000012",
            "bankAccountName": "Noresh",
            "bankAccountNumber": "9009120939129",
            "ifscCrossCheck": false,
            "payerVpa": "customer@vpa"
          },
          "id": "1af36b4e-681e-48a2-a15c-3b92da00e4c4",
          "shortUrl": "https://sandbox.bills.pe/vnl056cniwrk",
          "status": "BAV_REVERSE_PENNY_DROP_PAYMENT_SUCCESSFUL",
          "traceId": "1-6348f366-55c47bbe132d78441bbe4623",
          "upiBillId": "1005100812449350916",
          "upiLink": "upi://pay?pa=bauvatest@kaypay&pn=BauvaTest&am=1.00&tr=1005100812449350916&tn=Account%20Verification&cu=INR&mode=04",
          "validUpto": "2022-10-14T05:30:23.683631"
        }
      },
      "Data3": {
        "title": "Data3",
        "required": [
          "accountType",
          "bankAccountIfsc",
          "bankAccountName",
          "bankAccountNumber",
          "ifscCrossCheck",
          "payerVpa"
        ],
        "type": "object",
        "properties": {
          "accountType": {
            "type": "string"
          },
          "bankAccountIfsc": {
            "type": "string"
          },
          "bankAccountName": {
            "type": "string"
          },
          "bankAccountNumber": {
            "type": "string"
          },
          "ifscCrossCheck": {
            "type": "boolean"
          },
          "payerVpa": {
            "type": "string"
          }
        },
        "example": {
          "accountType": "UNKNOWN",
          "bankAccountIfsc": "SETU0000012",
          "bankAccountName": "Noresh",
          "bankAccountNumber": "9009120939129",
          "ifscCrossCheck": false,
          "payerVpa": "customer@vpa"
        }
      },
      "Failure-NotFound1": {
        "title": "Failure-NotFound1",
        "required": [
          "error"
        ],
        "type": "object",
        "properties": {
          "error": {
            "$ref": "#/components/schemas/Error"
          }
        },
        "example": {
          "error": {
            "code": "request_not_found",
            "detail": "Unable to find the BAV reverse penny drop request.",
            "traceId": "1-6348f37d-0a98296b43325b78627a65a7"
          }
        }
      }
    },
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [
    {
      "bearer": []
    }
  ],
  "tags": [
    {
      "name": "Reverse Penny Drop"
    },
    {
      "name": "Auth",
      "description": ""
    }
  ]
}
